export const styles = {
  container: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
    position: "relative" as const,
  },
  canvasContainer: {
    flex: 1,
    backgroundColor: "#000000",
    borderRadius: "8px",
    overflow: "hidden",
    position: "relative" as const,
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  canvas: {
    width: "100%",
    height: "100%",
    display: "block",
  },
  overlayLabel: {
    position: "absolute" as const,
    top: "8px",
    right: "8px",
    fontSize: "12px",
    color: "rgba(255, 255, 255, 0.3)",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    padding: "4px 8px",
    borderRadius: "4px",
    userSelect: "none" as const,
  },
  topbar: {
    position: "absolute" as const,
    top: 10,
    left: 10,
    zIndex: 10,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: "50px",
    padding: "4px",
    border: "1px solid rgba(255,255,255,0.1)",
    display: "flex",
    gap: "4px",
  },
  iconButton: {
    background: "transparent",
    border: "none",
    borderRadius: "50%",
    padding: "8px",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.7,
  },
};
