export const styles = {
  container: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
    position: "relative" as const,
  },
  canvasContainer: {
    flex: 1,
    backgroundColor: "#000000",
    borderRadius: "8px",
    overflow: "hidden",
    position: "relative" as const,
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  canvas: {
    width: "100%",
    height: "100%",
    display: "block",
  },
  overlayLabel: {
    position: "absolute" as const,
    top: "8px",
    right: "8px",
    fontSize: "12px",
    color: "rgba(255, 255, 255, 0.3)",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    padding: "4px 8px",
    borderRadius: "4px",
    userSelect: "none" as const,
  },
  topbar: {
    position: "absolute" as const,
    top: 10,
    left: 10,
    right: 10,
    zIndex: 10,
    backgroundColor: "rgba(0,0,0,0.8)",
    borderRadius: "12px",
    padding: "8px 16px",
    border: "1px solid rgba(255,255,255,0.2)",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  iconButton: {
    background: "transparent",
    border: "none",
    borderRadius: "50%",
    padding: "8px",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.7,
  },
  startButton: {
    marginLeft: "auto",
    backgroundColor: "#4CAF50",
    color: "white",
    display: "flex",
    alignItems: "center",
    gap: "5px",
    padding: "0 15px",
    borderRadius: "5px",
    cursor: "pointer",
    border: "none",
    height: "36px",
    fontSize: "14px",
    fontWeight: "bold",
  },
  overlay: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  modal: {
    backgroundColor: "#1e1e1e",
    padding: "30px",
    borderRadius: "12px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    textAlign: "center" as const,
    color: "white",
    minWidth: "300px",
  },
  wordButton: {
    backgroundColor: "#333",
    color: "white",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    padding: "10px 20px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "16px",
    flex: 1,
    transition: "background-color 0.2s",
  },
};
