export const styles = {
    container: {
        display: "flex",
        flexDirection: "column" as const,
        height: "100%",
        width: "100%",
    },
    messageList: {
        flex: 1,
        overflowY: "auto" as const,
        padding: "12px 16px",
        display: "flex",
        flexDirection: "column" as const,
        gap: "12px",
    },
    emptyState: {
        textAlign: "center" as const,
        color: "rgba(255, 255, 255, 0.4)",
        fontSize: "14px",
        marginTop: "24px",
    },
    messageRow: {
        display: "flex",
        alignItems: "flex-end",
        gap: "8px",
        marginBottom: "4px",
    },
    ownMessageRow: {
        flexDirection: "row-reverse" as const,
    },
    avatarContainer: {
        width: "30px",
        height: "30px",
        borderRadius: "50%",
        overflow: "hidden",
        flexShrink: 0,
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        border: "1.5px solid rgba(255, 255, 255, 0.15)",
        boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    },
    avatarImg: {
        width: "100%",
        height: "100%",
        objectFit: "cover" as const,
    },
    bubble: {
        maxWidth: "80%",
        padding: "10px 16px",
        borderRadius: "20px",
        fontSize: "14px",
        lineHeight: "1.5",
        wordBreak: "break-word" as const,
        position: "relative" as const,
        transition: "transform 0.2s ease, box-shadow 0.2s ease",
    },
    otherBubble: {
        backgroundColor: "rgba(45, 45, 45, 0.8)",
        color: "#f0f0f0",
        borderBottomLeftRadius: "4px",
        border: "1px solid rgba(255, 255, 255, 0.05)",
    },
    ownBubble: {
        background: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
        color: "#ffffff",
        borderBottomRightRadius: "4px",
        boxShadow: "0 4px 12px rgba(16, 185, 129, 0.25)",
    },
    senderName: {
        fontSize: "11px",
        color: "rgba(255, 255, 255, 0.5)",
        fontWeight: 700,
        marginBottom: "4px",
        display: "block",
        letterSpacing: "0.5px",
        textTransform: "uppercase" as const,
    },
    inputArea: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        padding: "12px",
        borderTop: "1px solid rgba(255, 255, 255, 0.1)",
        backgroundColor: "rgba(0, 0, 0, 0.2)",
    },
    input: {
        flex: 1,
        backgroundColor: "rgba(255, 255, 255, 0.1)",
        borderRadius: "9999px",
        padding: "8px 16px",
        fontSize: "14px",
        color: "#ffffff",
        border: "none",
        outline: "none",
    },
    sendButton: {
        width: "36px",
        height: "36px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "50%",
        backgroundColor: "#10b981",
        border: "none",
        opacity: 0.6,
    },
};
