export const WORDS = [
    "APPLE", "BANANA", "CHERRY", "DRAGON", "ELEPHANT", "FLAMINGO", "GUITAR", "HAMSTER",
    "ICEBERG", "JUNGLE", "KANGAROO", "LAPTOP", "MOUNTAIN", "NOTEBOOK", "OCTOPUS", "PENGUIN",
    "QUARTZ", "RABBIT", "SUNFLOWER", "TELESCOPE", "UMBRELLA", "VOLCANO", "WATERFALL", "XYLOPHONE",
    "YACHT", "ZEBRA", "ASTRONAUT", "BICYCLE", "CACTUS", "DOLPHIN", "EAGLE", "FIREWORKS",
    "GIRAFFE", "HELICOPTER", "ISLAND", "JELLYFISH", "KOALA", "LIGHTHOUSE", "MUSHROOM", "NEPTUNE",
    "ORANGE", "PYRAMID", "QUEEN", "RAINBOW", "SNOWMAN", "TRAIN", "UNICORN", "VAMPIRE", "WIZARD",
    "X-RAY", "YOYO", "ZOMBIE"
];

export const GAME_SETTINGS = {
    ROUNDS: 3,
    SELECT_WORD_TIME: 15000, // 15 seconds
    DRAW_TIME: 60000,        // 60 seconds
    POINTS_PER_GUESS: 100,
    BONUS_FOR_DRAWER: 20
};
