export const WORDS = [
    "APPLE", "BANANA", "CHERRY", "DRAGON", "ELEPHANT", "FLAMINGO", "GUITAR", "HAMSTER",
    "ICEBERG", "JUNGLE", "KANGAROO", "LAPTOP", "MOUNTAIN", "NOTEBOOK", "OCTOPUS", "PENGUIN",
    "QUARTZ", "RABBIT", "SUNFLOWER", "TELESCOPE", "UMBRELLA", "VOLCANO", "WATERFALL", "XYLOPHONE",
    "YACHT", "ZEBRA", "ASTRONAUT", "BICYCLE", "CACTUS", "DOLPHIN", "EAGLE", "FIREWORKS",
    "GIRAFFE", "HELICOPTER", "ISLAND", "JELLYFISH", "KOALA", "LIGHTHOUSE", "MUSHROOM", "NEPTUNE",
    "ORANGE", "PYRAMID", "QUEEN", "RAINBOW", "SNOWMAN", "TRAIN", "UNICORN", "VAMPIRE", "WIZARD",
    "X-RAY", "YOYO", "ZOMBIE", "ANCHOR", "ANTENNA", "AQUARIUM", "ARROW", "ATLAS", "AVALANCHE", "AVOCADO", "AXOLOTL", "ASTEROID", "AIRPLANE",
    "BALLOON", "BAMBOO", "BAROMETER", "BASILISK", "BATTERY", "BEACON", "BINOCULARS", "BLIZZARD", "BLUEPRINT", "BONFIRE",
    "CALENDAR", "CANYON", "CAROUSEL", "CATAPULT", "CELESTIAL", "CHAMELEON", "CHARGER", "CITADEL", "COMPASS", "CONSTELLATION",
    "DANDELION", "DEEPSEA", "DESERT", "DIAMOND", "DINOSAUR", "DOCKYARD", "DRONE", "DYNAMITE", "DAYBREAK", "DUSTSTORM",
    "ECLIPSE", "ECOSYSTEM", "ELECTRON", "EMERALD", "ENIGMA", "EQUATOR", "ESCALATOR", "ESTUARY", "EVEREST", "EXPLORER",
    "FABRIC", "FALCON", "FANTASY", "FARMHOUSE", "FEATHER", "FERRY", "FJORD", "FLASHLIGHT", "FOUNTAIN", "FREEZER",
    "GALAXY", "GARGOYLE", "GEYSER", "GLACIER", "GLOBE", "GONDOLA", "GRANITE", "GREENHOUSE", "GRIDLINE", "GYROSCOPE",
    "HABITAT", "HAMMOCK", "HARVEST", "HEADPHONES", "HEDGEHOG", "HORIZON", "HURRICANE", "HYDROGEN", "HYDRAULIC", "HYPERSPACE",
    "ICECAP", "IGLOO", "ILLUSION", "IMPULSE", "INCUBATOR", "INFRARED", "INSECT", "INSTRUMENT", "ISOTOPE", "IVORY",
    "JACKPOT", "JETPACK", "JEWELRY", "JOURNAL", "JUBILEE", "JUNCTION", "JUPITER", "JAVELIN", "JIGSAW", "JUKEBOX",
    "KAYAK", "KEYBOARD", "KILOMETER", "KINETIC", "KINGDOM", "KIOSK", "KITE", "KNEECAP", "KNOTWORK", "KRYPTON",
    "LABYRINTH", "LAGOON", "LANTERN", "LASER", "LATITUDE", "LEVER", "LIBRARY", "LIMESTONE", "LOCKSMITH", "LUNAR",
    "MAGNET", "MANDOLIN", "MAPLE", "MARINA", "MEADOW", "METEOR", "MICROSCOPE", "MIRAGE", "MONSOON", "MOTORWAY",
    "NARWHAL", "NAVIGATOR", "NECTAR", "NEBULA", "NEON", "NETWORK", "NEURON", "NIGHTFALL", "NOMAD", "NORTHSTAR",
    "OASIS", "OBELISK", "OBSERVATORY", "OCEANIC", "ODYSSEY", "OFFSHORE", "OMEGA", "ORBIT", "ORCHARD", "OXIDE",
    "PALACE", "PARACHUTE", "PATHWAY", "PENDULUM", "PHANTOM", "PHOTON", "PIONEER", "PLATEAU", "POLARIS", "PROPELLER",
    "QUADRANT", "QUANTUM", "QUARRY", "QUASAR", "QUEENSLAND", "QUIVER", "QUOTIENT", "QUICKSAND", "QUIETUDE", "QUILL",
    "RADAR", "RAINFOREST", "RAMPART", "REACTOR", "RELIC", "RESERVOIR", "RIPTIDE", "ROVER", "RUBICON", "RUNWAY",
    "SAFFRON", "SATELLITE", "SCULPTURE", "SEISMIC", "SERPENT", "SILHOUETTE", "SKYLIGHT", "SOLSTICE", "SPARKPLUG", "SUNDIAL",
    "TABLET", "TACTILE", "TEAKWOOD", "THUNDERBOLT", "TIMELINE", "TORNADO", "TRIANGLE", "TURBINE", "TWILIGHT", "TYPEWRITER",
    "VACUUM", "VALLEY", "VEGETABLE", "VEHICLE", "VELVET", "VETERAN", "VIBRATION", "VILLAGE", "VOLTAGE", "VOLCANO",
    "WAFFLE", "WALKWAY", "WARRANTY", "WATERMELON", "WAVE", "WEAPON", "WEATHER", "WHALE", "WHEAT", "WHEEL",
    "WIGWAM", "WINDMILL", "WINDOW", "WINTER", "WIZARD", "WONDER", "WORKSHOP", "WORLD", "WRISTWATCH", "WYVERN",
    "XENON", "XYLOPHONE", "XEROX", "XENOPHOBE", "XENOTRANSPLANT", "XENOGRAFT", "XENOLITH", "XENOGAMY", "XENOGLOSSIA", "XENOGON",
    "YACHT", "YARDSTICK", "YARN", "YAWN", "YEAST", "YELL", "YELLOW", "YETI", "YOGA", "YOLK",
    "ZEBRA", "ZEPHYR", "ZERO", "ZIGZAG", "ZINC", "ZIPPER", "ZODIAC", "ZONE", "ZOO", "ZYGOTE"
];

export const GAME_SETTINGS = {
    ROUNDS: 3,
    SELECT_WORD_TIME: 15000, // 15 seconds
    DRAW_TIME: 60000,        // 60 seconds
    POINTS_PER_GUESS: [100, 60, 30.10],
    BONUS_FOR_DRAWER: 20
};
